baseurl: /
url: https://sandstorm.org
permalink: /news/:year-:month-:day-:title
kramdown:
  syntax_highlighter: none
exclude:
  - Guardfile
  - Gemfile
  - Gemfile.lock
  - "sandstorm.io.*"
  - README.md
  - "*.sh"
  - vendor
gems:
  - octopress-autoprefixer
plugins:
  - jekyll-paginate-v2
pagination:
  enabled: true
  debug: true
  per_page: 5
  permalink: /page:num/
  sort_field: 'date'
  sort_reverse: true